---
data_root_path: "/home/alinle/data/"            # raw data path
dataset_path: "/home/alinle/dataset/"     # preprocessed data save/load path
model_save_path: "/home/alinle/model/"                # model save path

preprocess:
  flag: False                                            # true: preprocess, false: not preprocess

  common:
    process_num: 10                                       # number of task per process for multiprocessing
    type: CONT                                           # "DIFF" or "CONT"
    fixed_position: 1                                    # 0: face tracking, 1: fixed position
    face_detect_algorithm: 1                             # 1: face recognition, 2: FaceMesh
    larger_box_coef: 1.5
    image_size: 64                                     # cropped image size

  train_dataset:
    name: UBFC                                           # dataset name
    select_data:                                         # Empty the list if you want to select all person/task/source
      flag: False                                        # False if you want to select all data
      person_list: [ ]                                   # If V4V dataset, fill in the format 'Fxxx' or 'Mxxx'
      task_list: [ ]                                     # Scenario/Task Number specified in the dataset
      source_list: [ ]                                   # Fill only in case of VIPL_HR dataset.

  test_dataset:
    name: UBFC                                           # dataset name
    select_data:                                         # Empty the list if you want to select all person/task/source
      flag: False                                        # False if you want to select all data
      person_list: [ ]                                   # If V4V dataset, fill in the format 'Fxxx' or 'Mxxx'
      task_list: [ ]                                     # Scenario/Task Number specified in the dataset
      source_list: [ ]                                   # Fill only in case of VIPL_HR dataset.


wandb:
  flag: false
  project_name: rppg
  entity: daeyeolkim


fit:
  model: PhysNet
  type: CONT
  time_length: 32
  overlap_interval: 0 # default 0
  img_size: 64
  train_flag: True
  eval_flag: True
  eval_interval: 100
  debug_flag: false                        # True: debug mode (load small dataset, False: normal mode
  model_save_flag: False                   # True: save model, False: not save model

  train:
    dataset: UBFC
    shuffle: True
    fs: 30 #video fps
    batch_size: 8
    learning_rate: 0.009
    epochs: 30
    loss: MSE
    optimizer: AdamW
    meta:
      flag: false
      inner_optim: adam
      inner_loss: MSE
      inner_lr: 0.01

  test:
    dataset: UBFC
    shuffle: True
    fs: 30 #video fps
    batch_size: 8
    vital_type: HR                             # HR or HRV
    cal_type: FFT                              # PEAK or FFT
#    bpf: [0.75, 2.5]                            # None: None / 60~100bpm : [1, 1.67] / 45~150bpm : [0.75, 2.5]
    bpf: None                            # None: None / 60~100bpm : [1, 1.67] / 45~150bpm : [0.75, 2.5]
    metric: [ 'MAE','RMSE','MAPE','Pearson' ]
    eval_time_length: 10 # second